import { test, expect } from "@playwright/test";

test("spatial E1 debug shows households, journeys, cargo and food brought home", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?e1=debug");
  await expect(page.getByRole("heading", { name: "20人の集落 · 空間デバッグ" })).toBeVisible();
  await expect(page.locator(".e1-site")).toHaveCount(6);
  await expect(page.locator(".e1-person")).toHaveCount(20);
  await expect(page.locator(".e1-detail")).toContainText("F0、F1、B0、D0、D1");
  await page.getByRole("button", { name: "荷車 cart_1" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("食料積載: 0/21食");
  await page.locator(".e1-cash").filter({ has: page.locator("title", { hasText: "chest_H0" }) }).click();
  await expect(page.locator(".e1-inspector")).toContainText("現金: 40/100通貨");
  await page.locator(".e1-person").filter({ hasText: "B0" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("運べる食料: 0/5食");
  const farmer = page.locator(".e1-person").filter({ hasText: "F0" }).locator("circle");
  const homeX = Number(await farmer.getAttribute("cx"));
  await page.getByLabel("経過分").fill("345");
  const roadX = Number(await farmer.getAttribute("cx"));
  expect(roadX).toBeLessThan(homeX);
  expect(roadX).toBeGreaterThan(165);
  await page.getByLabel("経過分").fill("751");
  await expect(page.locator(".e1-stats span").filter({ hasText: "荷車" })).toContainText("21");
  await page.getByRole("button", { name: "荷車 cart_1" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("食料積載: 21/21食");
  await page.getByLabel("経過分").fill("830");
  await page.locator(".e1-cash").filter({ has: page.locator("title", { hasText: "pouch_B0" }) }).click();
  await expect(page.locator(".e1-inspector")).toContainText("現金: 10/20通貨");
  await page.getByLabel("経過分").fill("930");
  await expect(page.getByText("置かれた食料: 5食")).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: "artifacts/e1-spatial-debug.png", fullPage: true });
  await page.getByLabel("経過分").fill("1140");
  await expect(page.getByText("置かれた食料: 0食")).toBeVisible();
  await page.getByLabel("シナリオ").selectOption("carrier-absent");
  await page.getByLabel("経過分").fill("2880");
  await expect(page.locator(".e1-stats span").filter({ hasText: "農場" })).toContainText("21");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  expect(errors).toEqual([]);
});

test("physical E1 v2 debug shows parent, owner, capacity and causal work", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?e1=v2");
  await expect(page.getByRole("heading", { name: "20人の集落 · 物体木デバッグ" })).toBeVisible();
  await expect(page.locator(".e1-person")).toHaveCount(20);
  await page.getByRole("button", { name: "荷車 cart_1" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("物理親: market");
  await expect(page.locator(".e1-inspector")).toContainText("所有者: cooperative");
  await expect(page.locator(".e1-inspector")).toContainText("車両状態: 100/100");
  await page.getByLabel("経過分").fill("751");
  await expect(page.getByTestId("cart-load")).toContainText("21/21");
  await expect(page.locator(".e1-inspector")).toContainText("物理親: transit_");
  await expect(page.locator(".e1-inspector")).toContainText("車両状態: 96/100");
  await page.locator(".e1-person").filter({ hasText: "C" }).click();
  await expect(page.locator(".e1-detail")).toContainText("delivery_replanned");
  await expect(page.locator(".e1-detail")).toContainText("体力: 64");
  await expect(page.locator(".e1-detail")).toContainText("work_effort_paid");
  await page.getByLabel("経過分").fill("930");
  await expect(page.locator(".e1-stats span").filter({ hasText: "協同事業" })).toContainText("40");
  await page.getByLabel("シナリオ").selectOption("carrier-absent");
  await page.getByLabel("経過分").fill("2880");
  await expect(page.locator(".e1-stats span").filter({ hasText: "農場" })).toContainText("21");
  expect(errors).toEqual([]);
});

test("A2 map shows buyer, seller, farmer, and carrier decisions with physical goods", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?e1=a2");
  await expect(page.getByRole("heading", { name: "20人の集落 · 買物・販売・農業・運搬の自律デバッグ" })).toBeVisible();
  await page.locator(".e1-person").filter({ hasText: "B0" }).click();
  await page.getByLabel("経過分").fill("300");
  await expect(page.locator(".e1-detail")).toContainText("buyer_decided · post_order");
  await expect(page.locator(".e1-detail")).toContainText("次の判断:");
  await page.getByLabel("経過分").fill("930");
  await expect(page.locator(".e1-detail")).toContainText("buyer_decided · settle_sale,return_home");
  await expect(page.locator(".e1-stats span").filter({ hasText: "協同事業" })).toContainText("40");
  await page.locator(".e1-person").filter({ hasText: "S" }).click();
  await expect(page.locator(".e1-detail")).toContainText("seller_decided · finish_market_sale,return_home");
  await expect(page.locator(".e1-detail")).toContainText("市場で見た注文:");
  await page.locator(".e1-person").filter({ hasText: "F0" }).click();
  await expect(page.locator(".e1-detail")).toContainText("farmer_decided · harvest,return_home");
  await expect(page.locator(".e1-detail")).toContainText("本日の収穫: 完了");
  await page.locator(".e1-person").filter({ hasText: "C" }).click();
  await expect(page.locator(".e1-detail")).toContainText("carrier_decided · unload,return_home");
  await expect(page.locator(".e1-detail")).toContainText("現地で受けた配送:");
  expect(errors).toEqual([]);
});

test("A3 income map exposes earned and paid wages plus the effect of missed meals", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?e1=a3-income");
  await expect(page.getByRole("heading", { name: "20人の集落 · 実働・賃金・欠食の検証" })).toBeVisible();
  await page.getByLabel("経過分").fill("2880");
  await page.locator(".e1-person").filter({ hasText: "F0" }).click();
  await expect(page.locator(".e1-detail")).toContainText("賃金請求: 4通貨 · 支払済: 4通貨");
  await expect(page.locator(".e1-detail")).toContainText("世帯分配:");
  await page.locator(".e1-person").filter({ hasText: "C" }).click();
  await expect(page.locator(".e1-detail")).toContainText("vehicle_maintained");
  await expect(page.locator(".e1-stats")).toContainText("荷車の状態 100/100");
  await page.getByLabel("シナリオ").selectOption("buyer-no-money");
  await page.getByLabel("経過分").fill("2880");
  await page.locator(".e1-person").filter({ hasText: "F0" }).click();
  await expect(page.locator(".e1-detail")).toContainText("体力: 98 · 空腹: 2");
  await page.locator(".e1-person").filter({ hasText: "B0" }).click();
  await expect(page.locator(".e1-detail")).toContainText("wage_paid");
  expect(errors).toEqual([]);
});

test("A1 workbench shows tool handoff, progress, and both workers", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?a1=debug");
  await expect(page.getByRole("heading", { name: "二人と一つの道具 · 自律行動デバッグ" })).toBeVisible();
  await expect(page.getByTestId("a1-claim")).toHaveText("worker_a");
  await page.getByRole("button", { name: "働き手B worker_b" }).locator("circle").click();
  await expect(page.locator(".e1-inspector")).toContainText("待機中");
  await page.getByLabel("A1経過分").fill("3");
  await expect(page.getByTestId("a1-claim")).toHaveText("worker_b");
  await expect(page.locator(".e1-inspector")).toContainText("作業中");
  await page.getByLabel("A1経過分").fill("6");
  await expect(page.getByTestId("a1-claim")).toHaveText("なし");
  await expect(page.locator(".e1-inspector")).toContainText("体力: 7");
  await expect(page.locator(".e1-stats")).toContainText("完了 2/2");
  expect(errors).toEqual([]);
});
