import { test, expect } from "@playwright/test";

test("spatial E1 debug shows households, journeys, cargo and food brought home", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?e1=debug");
  await expect(page.getByRole("heading", { name: "20人の集落 · 空間デバッグ" })).toBeVisible();
  await expect(page.locator(".e1-site")).toHaveCount(6);
  await expect(page.locator(".e1-person")).toHaveCount(20);
  await expect(page.locator(".e1-detail")).toContainText("F0、F1、B0、D0、D1");
  await page.getByRole("button", { name: "荷車 cart_1" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("食料積載: 0/21食");
  await page.locator(".e1-cash").filter({ has: page.locator("title", { hasText: "chest_H0" }) }).click();
  await expect(page.locator(".e1-inspector")).toContainText("現金: 40/100通貨");
  await page.locator(".e1-person").filter({ hasText: "B0" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("運べる食料: 0/5食");
  const farmer = page.locator(".e1-person").filter({ hasText: "F0" }).locator("circle");
  const homeX = Number(await farmer.getAttribute("cx"));
  await page.getByLabel("経過分").fill("345");
  const roadX = Number(await farmer.getAttribute("cx"));
  expect(roadX).toBeLessThan(homeX);
  expect(roadX).toBeGreaterThan(165);
  await page.getByLabel("経過分").fill("751");
  await expect(page.locator(".e1-stats span").filter({ hasText: "荷車" })).toContainText("21");
  await page.getByRole("button", { name: "荷車 cart_1" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("食料積載: 21/21食");
  await page.getByLabel("経過分").fill("830");
  await page.locator(".e1-cash").filter({ has: page.locator("title", { hasText: "pouch_B0" }) }).click();
  await expect(page.locator(".e1-inspector")).toContainText("現金: 10/20通貨");
  await page.getByLabel("経過分").fill("930");
  await expect(page.getByText("置かれた食料: 5食")).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: "artifacts/e1-spatial-debug.png", fullPage: true });
  await page.getByLabel("経過分").fill("1140");
  await expect(page.getByText("置かれた食料: 0食")).toBeVisible();
  await page.getByLabel("シナリオ").selectOption("carrier-absent");
  await page.getByLabel("経過分").fill("2880");
  await expect(page.locator(".e1-stats span").filter({ hasText: "農場" })).toContainText("21");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  expect(errors).toEqual([]);
});

test("physical E1 v2 debug shows parent, owner, capacity and causal work", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?e1=v2");
  await expect(page.getByRole("heading", { name: "20人の集落 · 物体木デバッグ" })).toBeVisible();
  await expect(page.locator(".e1-person")).toHaveCount(20);
  await page.getByRole("button", { name: "荷車 cart_1" }).click();
  await expect(page.locator(".e1-inspector")).toContainText("物理親: market");
  await expect(page.locator(".e1-inspector")).toContainText("所有者: cooperative");
  await page.getByLabel("経過分").fill("751");
  await expect(page.locator(".e1-stats span").filter({ hasText: "荷車" })).toContainText("21/21");
  await expect(page.locator(".e1-inspector")).toContainText("物理親: transit_");
  await page.locator(".e1-person").filter({ hasText: "C" }).click();
  await expect(page.locator(".e1-detail")).toContainText("delivery_replanned");
  await page.getByLabel("経過分").fill("930");
  await expect(page.locator(".e1-stats span").filter({ hasText: "協同事業" })).toContainText("40");
  await page.getByLabel("シナリオ").selectOption("carrier-absent");
  await page.getByLabel("経過分").fill("2880");
  await expect(page.locator(".e1-stats span").filter({ hasText: "農場" })).toContainText("21");
  expect(errors).toEqual([]);
});
