import { expect, test } from "@playwright/test";

test("land economy recording opens from the browser route and shows timed person history", async ({ page }) => {
  await page.goto("/?village=land-economy");
  await expect(page.getByRole("heading", { name: "土地経済90日 · 空間デバッグ" })).toBeVisible();
  await expect(page.getByText("穀物の食事")).toBeVisible();
  const map = page.getByRole("img", { name: "土地経済の1280×768ピクセル地図" });
  await expect(map).toBeVisible();
  await expect(map).toHaveAttribute("width", "1280");
  await expect(map).toHaveAttribute("height", "768");
  await expect(page.getByText("32ピクセル×40列×24行")).toBeVisible();
  await map.click({ position: { x: 15 * 32 + 16, y: 9 * 32 + 16 } });
  await expect(page.getByRole("heading", { name: "選択セル 15,9" })).toBeVisible();
  await expect(page.getByText(/野草 .* \d+ · 動物なし/)).toBeVisible();
  await expect(page.getByRole("heading", { name: "F の判断履歴" })).toBeVisible();
  await expect(page.getByText(/経路 表示なし/)).toBeVisible();
  await page.getByLabel("経路の行先").selectOption("herb_patch");
  await expect(page.getByText(/経路 3セル/)).toBeVisible();
  const routePixel = await map.evaluate((canvas: HTMLCanvasElement) =>
    canvas.getContext("2d")!.getImageData(15 * 32 + 16, 11 * 32 + 16, 1, 1).data[0]);
  expect(routePixel).toBeGreaterThan(200);
  await page.getByLabel("経路の行先").selectOption("");
  const minute = page.getByLabel("土地経済の分");
  await expect(minute).toBeVisible();
  await expect(page.getByLabel("移動の刻み")).toHaveValue("5");
  await expect(page.getByText(/現在のセル: 16,12/)).toBeVisible();
  await minute.fill("10");
  await expect(page.getByText(/現在のセル: 15,11/)).toBeVisible();
  await page.getByLabel("移動の刻み").selectOption("15");
  await minute.fill("15");
  await expect(page.getByText(/現在のセル: 15,11/)).toBeVisible();
  await page.getByLabel("移動の刻み").selectOption("30");
  await minute.fill("30");
  await expect(page.getByText(/現在のセル: 15,9/)).toBeVisible();
  await page.getByLabel("移動の刻み").selectOption("60");
  await minute.fill("60");
  await expect(page.getByText(/現在のセル: 16,12/)).toBeVisible();
  await page.getByLabel("移動の刻み").selectOption("5");
  await page.getByLabel("土地経済の時刻").fill("2");
  await page.getByRole("button", { name: "＋1刻み" }).click();
  await expect(page.getByText("1日目 01:05")).toBeVisible();
  await page.getByLabel("土地経済の時刻").fill("2");
  await page.getByRole("button", { name: "再生" }).click();
  await expect(page.getByRole("status")).toContainText("再生中");
  await expect.poll(() => minute.inputValue()).not.toBe("0");
  await page.getByRole("button", { name: "停止" }).click();
  await expect(page.getByRole("status")).toContainText("停止中");
  const stoppedClock = await page.locator("strong[aria-live='polite']").textContent();
  const stoppedMinute = await minute.inputValue();
  await page.waitForTimeout(550);
  await expect(page.locator("strong[aria-live='polite']")).toHaveText(stoppedClock!);
  await page.getByRole("button", { name: "早送り ×4" }).click();
  await expect(page.getByRole("status")).toContainText("早送り中");
  await expect.poll(() => minute.inputValue()).not.toBe(stoppedMinute);
  await page.getByRole("button", { name: "停止" }).click();
  await page.getByLabel("土地経済の日").fill("90");
  await page.getByLabel("土地経済の時刻").fill("24");
  await minute.fill("60");
  await expect(page.getByText("90日目 24:00")).toBeVisible();
  await expect(page.locator(".e1-stats span").filter({ hasText: "穀物の食事" }).locator("b")).toHaveText("435");
  await expect(page.locator(".e1-stats span").filter({ hasText: "探索した植物の食事" }).locator("b")).toHaveText("3");
  await page.getByLabel("土地経済の人物").selectOption("C");
  await expect(page.getByRole("heading", { name: "C の判断履歴" })).toBeVisible();
  await page.getByLabel("経路の行先").selectOption("grain_plot_4");
  await expect(page.getByText(/経路 \d+セル/)).toBeVisible();
});
